// SPDX-License-Identifier: AGPL-3.0-only

//! Embed the operator console and the secret-input page (P04-D9) with
//! `include_bytes!`, so the controller is one artifact without a runtime
//! asset directory or an embedding dependency. Sources default to
//! `packages/console/dist` and `packages/browser-ui/dist-embedded` (built by
//! `npm run build`) and can be overridden with `BLINDPASS_CONSOLE_DIST` and
//! `BLINDPASS_INPUT_DIST`. A missing directory embeds nothing: that build
//! serves no UI.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn collect(root: &Path, directory: &Path, files: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = fs::read_dir(directory) else {
        return;
    };
    let mut entries: Vec<_> = entries.flatten().collect();
    entries.sort_by_key(|entry| entry.file_name());
    for entry in entries {
        let path = entry.path();
        let Ok(kind) = entry.file_type() else {
            continue;
        };
        if kind.is_dir() {
            collect(root, &path, files);
        } else if kind.is_file() {
            let relative = path.strip_prefix(root).expect("path under root");
            let name = relative.to_string_lossy().replace('\\', "/");
            // Source maps are for development only.
            if name.ends_with(".map") {
                continue;
            }
            files.push((format!("/{name}"), path));
        }
    }
}

fn table(name: &str, source: &Path, out: &mut String) {
    println!("cargo:rerun-if-changed={}", source.display());
    let mut files = Vec::new();
    if source.join("index.html").is_file() {
        collect(source, source, &mut files);
    }
    writeln!(out, "pub(crate) static {name}: &[(&str, &[u8])] = &[").unwrap();
    for (path, file) in files {
        let absolute = file.canonicalize().expect("canonical asset path");
        writeln!(
            out,
            "    ({path:?}, include_bytes!({:?})),",
            absolute.display().to_string()
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let repository = manifest.join("../..");
    println!("cargo:rerun-if-env-changed=BLINDPASS_CONSOLE_DIST");
    println!("cargo:rerun-if-env-changed=BLINDPASS_INPUT_DIST");
    let console = env::var_os("BLINDPASS_CONSOLE_DIST")
        .map(PathBuf::from)
        .unwrap_or_else(|| repository.join("packages/console/dist"));
    let input = env::var_os("BLINDPASS_INPUT_DIST")
        .map(PathBuf::from)
        .unwrap_or_else(|| repository.join("packages/browser-ui/dist-embedded"));
    let mut out = String::from("// Generated by build.rs.\n");
    table("CONSOLE_FILES", &console, &mut out);
    table("INPUT_FILES", &input, &mut out);
    let target = PathBuf::from(env::var("OUT_DIR").unwrap()).join("embedded_ui.rs");
    fs::write(target, out).unwrap();
}
