[package]
name = "blindpass-controller"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
p02-test-failpoints = []

[dependencies]
blindpass-core = { path = "../blindpass-core" }
argon2 = "0.5.3"
axum = { version = "0.8.4", features = ["json", "macros"] }
base64 = "0.22.1"
jsonwebtoken = "9.3.1"
rand = "0.8.5"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sqlx = { version = "0.8.6", default-features = false, features = [
    "macros",
    "migrate",
    "postgres",
    "runtime-tokio-rustls",
    "sqlite",
] }
tokio = { version = "1.47.0", features = [
    "macros",
    "net",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
tower-http = { version = "0.6.6", features = [
    "cors",
    "limit",
    "request-id",
    "sensitive-headers",
    "timeout",
    "trace",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }

[lints]
workspace = true
