// P07 / pilot S01: the confirmation code is human correlation text, never a
// credential. It is generated by the controller, returned in the request
// creation and metadata responses and nowhere accepted as input, so a code
// alone cannot authorize anything. The size of its space is recorded so a
// shrink is deliberate.
import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

function* walk(value, trail = []) {
  yield [trail, value];
  if (value && typeof value === "object") {
    for (const [key, child] of Object.entries(value)) yield* walk(child, [...trail, key]);
  }
}

test("the API names the code only in responses, never in a request parameter or body", async () => {
  const document = JSON.parse(await readFile(path.join(root, "docs/api/controller.openapi.yaml"), "utf8"));
  const requestSchemas = new Set();
  for (const [route, item] of Object.entries(document.paths)) {
    for (const [method, operation] of Object.entries(item)) {
      if (typeof operation !== "object" || !operation) continue;
      for (const parameter of operation.parameters ?? []) {
        assert.ok(!/code/i.test(parameter.name ?? parameter.$ref ?? ""), `${method} ${route} takes ${parameter.name} as a parameter`);
      }
      for (const [, value] of walk(operation.requestBody ?? {})) {
        if (typeof value === "string" && value.startsWith("#/components/schemas/")) requestSchemas.add(value.split("/").pop());
      }
    }
  }
  const schemas = document.components.schemas;
  const reach = (name, seen = new Set()) => {
    if (seen.has(name)) return seen;
    seen.add(name);
    for (const [, value] of walk(schemas[name])) {
      if (typeof value === "string" && value.startsWith("#/components/schemas/")) reach(value.split("/").pop(), seen);
    }
    return seen;
  };
  const inRequests = new Set([...requestSchemas].flatMap((name) => [...reach(name)]));
  for (const name of inRequests) {
    assert.ok(!JSON.stringify(schemas[name]).includes("confirmation_code"), `${name} is a request schema carrying a confirmation code`);
  }
  const carriers = Object.entries(schemas).filter(([, schema]) => JSON.stringify(schema).includes("confirmation_code")).map(([name]) => name).sort();
  assert.deepEqual(carriers, ["SecretMetadata", "SecretRequestCreated"]);
});

test("controller source never reads a confirmation code from a request", async () => {
  const routes = path.join(root, "crates/blindpass-controller/src/routes");
  const users = [];
  for (const name of await readdir(routes)) {
    if (!name.endsWith(".rs")) continue;
    const text = await readFile(path.join(routes, name), "utf8");
    if (text.includes("confirmation_code")) users.push(name);
  }
  assert.deepEqual(users, ["secrets.rs"], "only the secret-request route handles codes");
  const secrets = await readFile(path.join(routes, "secrets.rs"), "utf8");
  // Every use is generation, storage or response; none compares a supplied value.
  for (const line of secrets.split("\n").filter((entry) => entry.includes("confirmation_code"))) {
    assert.ok(!/(==|!=|constant_equal|verify)/.test(line), `a confirmation code is compared: ${line.trim()}`);
  }
});

test("the shared dictionary keeps at least 6,400 codes (about 12.6 bits): a correlation aid only", async () => {
  const fixture = JSON.parse(await readFile(path.join(root, "packages/contract-tests/fixtures/cv04-confirmation-code.json"), "utf8"));
  const space = fixture.adjectives.length * fixture.nouns.length * (fixture.number_max - fixture.number_min + 1);
  assert.ok(space >= 6_400, `code space shrank to ${space}`);
  // With this space two simultaneous pending requests collide about 1 time in
  // 6,400, and among 20 pending requests about 3% of the time: the page shows
  // the code beside the description so a human can tell requests apart, and the
  // link signature, not the code, authorizes the submission.
  const pending = 20;
  const noCollision = Array.from({ length: pending }, (_, index) => 1 - index / space).reduce((a, b) => a * b, 1);
  assert.ok(1 - noCollision < 0.05);
});
